######################################################
### DO NOT EDIT THIS FILE. Warranty Voided if      ###
### this channel file is edited from original      ###
###                                                ###
### M410 ch1.py V0.1                               ###
### For operating Modbus to Serial Adapter         ###
###                                                ###
### Created By Simon Maselli                       ###
### 24 July 2017                                   ###
###                                                ###
### Copyright Minnovation 2017                     ###
######################################################

from uModBus.serial import Serial
from uModBus.tcp import TCP

import machine, time, ustruct

sensorPower = machine.Pin('P20', mode=machine.Pin.OUT)
sensorPower.value(1)

def getData(P1,P2):
    uart_id = 0x01
    modbus_obj = Serial(uart_id, pins=(P1,P2))

    slave_addr=1
    starting_address=62594
    register_quantity=1
    signed=True
    result=''

    for y in range(0,2):
        try:
            register_value = modbus_obj.read_holding_registers(slave_addr, starting_address, register_quantity, signed)
            #print(register_value)
            #print(bytes(register_value[1]))
            result = ustruct.unpack('>f', register_value)
            #print(result[0])
            #print(result[1]-14.7)
        except Exception as e:
            print('Waking up Slave')
            pass
    try:
        return(result[0])
    except:
        return


#while True:
    #print(getData())
